<div class="controls">
    <?= $tabs ?>
    <?= $this->qlink(
        $this->translate('Add graph') ,
        'grafana/graph/new',
        null,
        [
            'class' => 'action-link',
            'data-base-target' => '_next',
            'icon' => 'plus',
            'title' => $this->translate('Add graph')
        ]
    ) ?>
</div>
<div class="content">
<?php /** @var \Icinga\Application\Config $graph */ if ($graphs->isEmpty()): ?>
    <p><?= $this->translate('No graph has been added yet.') ?></p>
<?php return; endif ?>
    <table class="grafana-graphs-table common-table table-row-selectable" data-base-target="_next">
        <thead>
            <tr>
                <th><?= $this->translate('Name') ?></th>
                <th><?= $this->translate('Dashboard') ?></th>
                <th><?= $this->translate('Dashboard UID') ?></th>
                <th><?= $this->translate('Panel ID') ?></th>
                <th><?= $this->translate('Custom Variables') ?></th>
                <th><?= $this->translate('Timerange') ?></th>
                <th><?= $this->translate('Height') ?></th>
                <th><?= $this->translate('Width') ?></th>
                <th><?= $this->translate('OrgID') ?></th>
                <th><?= $this->translate('Repeatable') ?></th>
                <th><?= $this->translate('Metrics per panel') ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($graphs as $name => $graph): /** @var object $role */ ?>
            <tr>
                <td>
                    <?= $this->qlink(
                        $name,
                        'grafana/graph/update',
                        ['graph' => $name],
                        ['title' => $this->translate('Update graph')]
                    ) ?>
                </td>
                <td><?= $this->escape($graph->dashboard) ?></td>
                <td><?= $this->escape($graph->dashboarduid) ?></td>
                <td><?= $this->escape($graph->panelId) ?></td>
                <td><?= isset($graph->customVars) ? "Yes" : "No" ?></td>
                <td><?= $this->escape($graph->timerange) ?></td>
                <td><?= $this->escape($graph->height) ?></td>
                <td><?= $this->escape($graph->width) ?></td>
                <td><?= $this->escape($graph->orgId) ?></td>
                <td><?= ($graph->repeatable == "yes" ) ? "Yes" : "No" ?></td>
                <td><?= ($graph->nmetrics >= 1 ) ? $this->escape($graph->nmetrics) : $this->translate('Not used') ?></td>
                <td class="icon-col text-right">
                    <?= $this->qlink(
                        '',
                        'grafana/graph/remove',
                        ['graph' => $name],
                        [
                            'class' => 'action-link',
                            'icon' => 'cancel',
                            'title' => $this->translate('Remove graph')
                        ]
                    ) ?>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
